server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:15432/ead-course-v2
    username: alvesbrian
    password: qwkdgt1874
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://ptnumalx:3J4tAfecpoN7tLpWCHTijezJn6y9CTly@campbell.lmq.cloudamqp.com/ptnumalx

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

course:
  refreshscope:
    name: Brian Alves UPDATE!!!!

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost
